import { eq, sql } from 'drizzle-orm'
import { z } from 'zod'
import { licenseKeys, licenses } from '@/db/schema'
import type { AnyDb, TenantTx } from '@/db/tenant'
import { withoutTenantScope, withTenant } from '@/db/tenant'
import { AppError, notFound } from '@/lib/errors'
import { newId } from '@/lib/ids'
import { writeAudit } from '@/lib/audit'
import type { RequestContext } from '@/server/context'
import { requirePermission } from '@/server/context'
import { recordLicenceEvent } from '@/billing/service'
import {
  generateProductKey,
  hashProductKey,
  isKnownDuration,
  keyLast4,
  normaliseProductKey,
} from './product-key'

/**
 * Issuing and activating product keys.
 *
 * The licensing path that does not go through Stripe. A key is generated by the
 * vendor for one organization and one term, handed over however the sale
 * happened, and activated to grant that term. It is how an offline customer, an
 * invoice-paying customer, or a reseller's customer gets licensed — and how the
 * desktop app will be licensed when it ships.
 *
 * The key is generated ONCE and stored only as a peppered hash. There is no
 * "show me that key again": if it is lost, issue another and revoke the first.
 */

/** How long an unactivated key stays redeemable. A key that was never used
 *  should not stay live for ever on a sticky note. */
const REDEEMABLE_DAYS = 365

export const issueSchema = z.object({
  organizationId: z.string().uuid(),
  durationDays: z.number().int().positive(),
  seatCount: z.number().int().positive().max(10_000).optional(),
  plan: z.string().max(40).optional(),
  note: z.string().max(300).optional(),
})

export type IssuedKey = {
  keyId: string
  /** Plaintext, returned EXACTLY once. Only a hash is stored. */
  key: string
  organizationId: string
  durationDays: number
  expiresAt: string
}

/**
 * Issues a key for one organization.
 *
 * Runs inside a transaction scoped to the TARGET tenant — a platform admin
 * issuing for org X sets the scope to X deliberately, rather than reaching
 * across tenants with RLS off. The cross-tenant part (which organizations exist
 * at all) is a separate, database-gated function.
 */
export async function issueProductKey(
  tx: TenantTx,
  input: unknown,
  actor: { userId: string | null },
): Promise<IssuedKey> {
  const parsed = issueSchema.safeParse(input)
  if (!parsed.success) {
    throw new AppError('VALIDATION_FAILED', 'Pick an organization and a term.', parsed.error.issues)
  }
  const { organizationId, durationDays, seatCount, plan, note } = parsed.data

  if (!isKnownDuration(durationDays)) {
    // Not a hard rule — the column takes any positive number so a bespoke term
    // can be issued — but an unexpected one is worth refusing from the UI,
    // where it is far more likely to be a slip than a decision.
    throw new AppError('VALIDATION_FAILED', 'Choose 3 days, 30 days or 1 year.')
  }

  const licence = (
    await tx
      .select({ id: licenses.id })
      .from(licenses)
      .where(eq(licenses.organizationId, organizationId))
      .limit(1)
  )[0]

  if (!licence) {
    throw new AppError(
      'NO_LICENSE',
      'That organization has no licence record to attach a key to.',
    )
  }

  // At most one live key per licence — `license_keys_one_active_uq` enforces
  // it. Issuing a replacement therefore SUPERSEDES the outstanding one rather
  // than colliding with it, which is also the behaviour you want: a customer
  // who says "the key never arrived" gets a new one, and the old one stops
  // working the moment it is reissued.
  await tx
    .update(licenseKeys)
    .set({ status: 'superseded' })
    .where(
      sql`${licenseKeys.organizationId} = ${organizationId}
          and ${licenseKeys.status} = 'active'
          and ${licenseKeys.activatedAt} is null`,
    )

  const key = generateProductKey()
  const keyId = newId()
  const expiresAt = new Date(Date.now() + REDEEMABLE_DAYS * 86_400_000)

  await tx.insert(licenseKeys).values({
    id: keyId,
    licenseId: licence.id,
    organizationId,
    keyHash: hashProductKey(key)!,
    keyLast4: keyLast4(key)!,
    status: 'active',
    durationDays,
    seatCount: seatCount ?? null,
    plan: plan ?? null,
    issuedBy: actor.userId,
    note: note ?? null,
    expiresAt,
  })

  await recordLicenceEvent(
    tx,
    organizationId,
    'key.issued',
    // The last four, never the key. An event log that records the credential is
    // a second copy of it.
    { keyLast4: keyLast4(key), durationDays, seatCount: seatCount ?? null, note: note ?? null },
    actor.userId,
  )

  await writeAudit(tx, {
    organizationId,
    actorUserId: actor.userId,
    action: 'license_key.issued',
    entityType: 'license_key',
    entityId: keyId,
    after: { keyLast4: keyLast4(key), durationDays, seatCount: seatCount ?? null },
  })

  return {
    keyId,
    key,
    organizationId,
    durationDays,
    expiresAt: expiresAt.toISOString(),
  }
}

/** Withdraws a key. An activated key stays activated — revoking it does not
 *  claw back a term already granted, which would strand a paying customer. */
export async function revokeProductKey(
  tx: TenantTx,
  organizationId: string,
  keyId: string,
  actor: { userId: string | null; reason?: string },
): Promise<void> {
  const updated = await tx
    .update(licenseKeys)
    .set({
      status: 'revoked',
      revokedAt: new Date(),
      revokedReason: actor.reason ?? null,
    })
    .where(eq(licenseKeys.id, keyId))
    .returning({ last4: licenseKeys.keyLast4 })

  if (!updated[0]) throw notFound('No such key.')

  await writeAudit(tx, {
    organizationId,
    actorUserId: actor.userId,
    action: 'license_key.revoked',
    entityType: 'license_key',
    entityId: keyId,
    after: { keyLast4: updated[0].last4, reason: actor.reason ?? null },
  })
}

// ---------------------------------------------------------------------------
// Activation
// ---------------------------------------------------------------------------

export type ActivationResult = {
  plan: string
  seats: number
  validUntil: string
  durationDays: number
}

/**
 * Redeems a key against the tenant it was issued for.
 *
 * Extends from whichever is LATER — today, or the licence's current expiry — so
 * activating early tops up rather than throws away time already paid for.
 * Somebody who renews a week before their year ends should get a year and a
 * week, not a year.
 */
export async function activateProductKey(
  db: AnyDb,
  ctx: RequestContext,
  rawKey: string,
): Promise<ActivationResult> {
  requirePermission(ctx, 'license.manage')

  const normalised = normaliseProductKey(rawKey)
  const hash = normalised ? hashProductKey(normalised) : null
  if (!hash) {
    throw new AppError('VALIDATION_FAILED', 'That does not look like a product key.')
  }

  // Pre-tenant lookup: the key carries which organization it belongs to, and
  // RLS would hide the row from a caller in a different tenant.
  const resolved = await withoutTenantScope(db, async (tx) => {
    const res = await tx.execute(sql`select * from public.resolve_license_key(${hash})`)
    return (
      res as unknown as {
        rows: {
          key_id: string
          organization_id: string
          license_id: string
          status: string
          plan: string | null
          duration_days: number | null
          seat_count: number | null
          expired: boolean
          activated: boolean
          revoked: boolean
        }[]
      }
    ).rows[0]
  })

  // Unknown and revoked are deliberately indistinguishable to somebody guessing.
  if (!resolved) throw new AppError('LICENSE_INVALID', 'That key is not valid.')

  if (resolved.organization_id !== ctx.organizationId) {
    // Named plainly rather than hidden: the person holding it needs to know
    // they are in the wrong workspace, and they already possess the key.
    throw new AppError(
      'LICENSE_INVALID',
      'That key was issued for a different organization. Switch to it and try again.',
    )
  }
  if (resolved.revoked) throw new AppError('LICENSE_INVALID', 'That key has been withdrawn.')
  if (resolved.activated) {
    throw new AppError('LICENSE_INVALID', 'That key has already been used.')
  }
  if (resolved.expired) {
    throw new AppError('LICENSE_INVALID', 'That key has expired and can no longer be redeemed.')
  }
  if (resolved.status !== 'active') {
    // Superseded — a newer key was issued for this organization, which is how a
    // reissue invalidates the one that went astray.
    throw new AppError(
      'LICENSE_INVALID',
      'That key has been replaced by a newer one. Use the most recent key you were sent.',
    )
  }

  const days = resolved.duration_days ?? 30

  return withTenant(db, { organizationId: ctx.organizationId, userId: ctx.userId }, async (tx) => {
    // Claim the key FIRST, and only if it is still unclaimed. Two clicks race
    // here; the second updates zero rows and is refused rather than granting
    // the term twice.
    const claimed = await tx
      .update(licenseKeys)
      .set({ activatedAt: new Date(), activatedBy: ctx.userId, status: 'superseded' })
      .where(
        sql`${licenseKeys.id} = ${resolved.key_id}
            and ${licenseKeys.activatedAt} is null
            and ${licenseKeys.revokedAt} is null
            and ${licenseKeys.status} = 'active'`,
      )
      .returning({ id: licenseKeys.id })

    if (!claimed[0]) throw new AppError('LICENSE_INVALID', 'That key has already been used.')

    const current = (
      await tx
        .select()
        .from(licenses)
        .where(eq(licenses.organizationId, ctx.organizationId))
        .limit(1)
    )[0]
    if (!current) throw new AppError('NO_LICENSE', 'This organization has no licence record.')

    const now = new Date()
    const from =
      current.validUntil && current.validUntil > now ? current.validUntil : now
    const validUntil = new Date(from.getTime() + days * 86_400_000)

    // Seats only ever go UP here. A key for fewer seats than are in use would
    // otherwise leave the seat trigger refusing every change.
    const seats = resolved.seat_count
      ? Math.max(resolved.seat_count, current.seatCount)
      : current.seatCount

    await tx
      .update(licenses)
      .set({
        plan: resolved.plan ?? current.plan,
        seatCount: seats,
        status: 'active',
        validUntil,
        // A key-licensed tenant is not in a payment-failure grace window.
        graceUntil: null,
        updatedAt: now,
      })
      .where(eq(licenses.organizationId, ctx.organizationId))

    await recordLicenceEvent(
      tx,
      ctx.organizationId,
      'key.activated',
      {
        keyId: resolved.key_id,
        durationDays: days,
        validUntil: validUntil.toISOString(),
        seats,
      },
      ctx.userId,
    )

    await writeAudit(tx, {
      organizationId: ctx.organizationId,
      actorUserId: ctx.userId,
      action: 'license_key.activated',
      entityType: 'license_key',
      entityId: resolved.key_id,
      before: { status: current.status, validUntil: current.validUntil?.toISOString() ?? null },
      after: { status: 'active', validUntil: validUntil.toISOString(), seats },
      requestId: ctx.requestId,
      ip: ctx.ip,
    })

    return {
      plan: resolved.plan ?? current.plan,
      seats,
      validUntil: validUntil.toISOString(),
      durationDays: days,
    }
  })
}
