import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { FlatCompat } from '@eslint/eslintrc'

/**
 * ESLint, flat config.
 *
 * `npm run lint` previously ran `next lint` with no configuration anywhere in
 * the repo, so it dropped into an interactive installer and asked which style
 * you wanted — which hangs forever in CI, where nothing is there to answer. A
 * script that cannot run unattended is worse than no script, because it looks
 * like a check that is being performed.
 *
 * `next lint` is also deprecated and disappears in Next 16, so this calls the
 * ESLint CLI directly rather than buying the same problem again later.
 *
 * `next/core-web-vitals` plus `next/typescript` is what create-next-app would
 * have produced. One rule is switched off below, with the reasoning; everything
 * else is left where Next put it.
 */
const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) })

const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'next-env.d.ts', // Generated by Next on every build; edits are discarded.
      'desktop/**', // Rust and its generated bindings; not this linter's job.
      'drizzle/**', // SQL.
      'src/invoices/fonts.ts', // Generated: a base64 font blob on one line.
    ],
  },

  ...compat.extends('next/core-web-vitals', 'next/typescript'),

  {
    rules: {
      /**
       * OFF, and this is the one judgement call in this file.
       *
       * The rule exists because webpack wraps each file in a CommonJS scope
       * where `module` is a real binding, and shadowing it at module scope
       * breaks the wrapper. Every occurrence here is block-scoped instead —
       * `for (const module of tableModules)`, `const module = moduleById(id)`
       * inside a component or a route handler — so webpack's binding is never
       * touched.
       *
       * "Module" is also this product's own vocabulary: there is a module
       * registry, a `[module]` route segment and a `moduleById` lookup.
       * Renaming that to `mod` in five files would make the code read worse to
       * satisfy a rule that is not describing a real problem in it.
       *
       * If a top-level `const module` is ever added, this rule will not catch
       * it. Nothing else in the toolchain will either — that is the cost.
       */
      '@next/next/no-assign-module-variable': 'off',

      /**
       * A warning, not an error. Rows come back from `tx.execute` untyped and
       * are cast through `unknown` at that boundary, deliberately and visibly.
       * Making it an error would push those casts somewhere less obvious rather
       * than remove them.
       */
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },
]

export default config
