import { randomBytes } from 'node:crypto'
import { existsSync } from 'node:fs'
import { writeFile } from 'node:fs/promises'
import path from 'node:path'

/**
 * Generates every production secret, once.
 *
 *   npm run gen:secrets
 *
 * Writes `.env.vercel` — gitignored, and the only copy. Nothing regenerates
 * these on demand: `ENCRYPTION_KEY` is not recoverable from the database, and
 * `LICENSE_KEY_PEPPER` cannot change after the first API key is issued without
 * invalidating every key already handed out.
 *
 * Refuses to overwrite an existing file. Re-running it after the secrets are in
 * use would silently produce a set that signs everyone out and orphans every
 * encrypted value — so that has to be a deliberate `--force`.
 *
 * `openssl rand -base64 32` does the same job; this exists because Windows
 * machines generally do not have openssl, and because getting ENCRYPTION_KEY to
 * decode to exactly 32 bytes by hand is a step people get wrong (32 base64
 * CHARACTERS is 24 bytes, which looks right and is not).
 */

const OUT = path.resolve(process.cwd(), '.env.vercel')
const force = process.argv.includes('--force')

/** base64 of exactly `bytes` random bytes. */
const key = (bytes: number) => randomBytes(bytes).toString('base64')

/** Passwords go into a URL, so base64url — no `+`, `/` or `=` to percent-encode
 *  and no chance of a connection string that works in one client and not
 *  another. */
const password = (bytes: number) => randomBytes(bytes).toString('base64url')

async function main() {
  if (existsSync(OUT) && !force) {
    console.error(
      `.env.vercel already exists.\n\n` +
        `Refusing to overwrite it. If these secrets are already deployed, regenerating\n` +
        `them signs every user out and makes every encrypted integration token\n` +
        `unreadable. If you are certain, re-run with --force.`,
    )
    process.exit(1)
  }

  const secrets = {
    AUTH_SECRET: key(32),
    // Must decode to EXACTLY 32 bytes — AES-256.
    ENCRYPTION_KEY: key(32),
    LICENSE_KEY_PEPPER: key(32),
    CRON_SECRET: password(32),
    SYNCRESE_OWNER_PASSWORD: password(24),
    SYNCRESE_APP_PASSWORD: password(24),
  }

  const body = `# Syncrèse — generated production secrets. NOT IN SOURCE CONTROL.
#
# Generated by \`npm run gen:secrets\`. This is the ONLY copy — put it in a
# password manager now, before you go any further.
#
# Losing these costs, respectively: every session (AUTH_SECRET), every
# encrypted integration token and MFA secret with no way to recover them
# (ENCRYPTION_KEY), and every API key ever issued (LICENSE_KEY_PEPPER).
#
# Back up ENCRYPTION_KEY somewhere that does NOT depend on the database backup.
# A database restore without it is a restore of unreadable ciphertext.

# --- application secrets (paste these into Vercel) -------------------------
AUTH_SECRET=${secrets.AUTH_SECRET}
ENCRYPTION_KEY=${secrets.ENCRYPTION_KEY}
LICENSE_KEY_PEPPER=${secrets.LICENSE_KEY_PEPPER}
CRON_SECRET=${secrets.CRON_SECRET}

# --- database role passwords (used by \`npm run db:provision\`) --------------
# These do NOT go into Vercel on their own — they end up inside DATABASE_URL
# and DATABASE_MIGRATION_URL, which db:provision prints for you.
SYNCRESE_OWNER_PASSWORD=${secrets.SYNCRESE_OWNER_PASSWORD}
SYNCRESE_APP_PASSWORD=${secrets.SYNCRESE_APP_PASSWORD}

# --- filled in during deployment -------------------------------------------
# The admin connection string from Neon. Used ONCE, by db:provision, and then
# never again — neither the app nor the migration job receives it.
DATABASE_ADMIN_URL=

# Printed by db:provision. Paste both into Vercel.
DATABASE_MIGRATION_URL=
DATABASE_URL=

# The public URL Vercel gives you, or your own domain. Must be https.
AUTH_URL=

# "open" only while you create the first organization.
SIGNUP_MODE=closed
`

  await writeFile(OUT, body, 'utf8')

  console.log(`Wrote ${OUT}\n`)
  console.log('  AUTH_SECRET             32 bytes  session signing')
  console.log('  ENCRYPTION_KEY          32 bytes  at-rest encryption — NOT RECOVERABLE')
  console.log('  LICENSE_KEY_PEPPER      32 bytes  API-key hashing — cannot change later')
  console.log('  CRON_SECRET             32 bytes  webhook dispatch + health detail')
  console.log('  SYNCRESE_OWNER_PASSWORD 24 bytes  schema owner')
  console.log('  SYNCRESE_APP_PASSWORD   24 bytes  application role')
  console.log(
    '\nThis file is gitignored and is the only copy. Put it in a password manager\n' +
      'before continuing, and back up ENCRYPTION_KEY separately from the database.\n',
  )
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err)
  process.exit(1)
})
